using Backend.Api.Common;
using Microsoft.AspNetCore.Mvc;

namespace Backend.Api.Workflows;

[ApiController]
[Route("api/admin/workflows")]
public sealed class WorkflowController : ControllerBase
{
    private readonly IWorkflowRepository _repo; private readonly IWorkflowCompiler _compiler;
    public WorkflowController(IWorkflowRepository repo, IWorkflowCompiler compiler) => (_repo, _compiler) = (repo, compiler);
    [HttpGet] public async Task<ActionResult<IReadOnlyList<WorkflowInfo>>> List(CancellationToken ct) { RequireManage(); return Ok(await _repo.ListAsync(Request.RequireTenant(), ct)); }
    [HttpGet("catalog/nodes")] public async Task<IActionResult> Catalog(CancellationToken ct) { RequireManage(); return Ok(await _compiler.CatalogAsync(Request.RequireTenant(), ct)); }
    [HttpGet("{id:guid}")] public async Task<ActionResult<WorkflowResponse>> Get(Guid id, CancellationToken ct) { RequireManage(); return WithTag(await _repo.GetAsync(Request.RequireTenant(), id, ct) ?? throw Missing(id)); }
    [HttpPost]
    public async Task<ActionResult<WorkflowResponse>> Create([FromBody] WorkflowUpsert request, CancellationToken ct)
    { RequireManage(); var name = Require(request.Name, "name"); var kind = Require(request.Kind, "kind"); var (def, ui) = Canonical(request); var errors = WorkflowCanonicalizer.ValidateEnvelope(kind, def, ui); if (errors.Count > 0) throw Invalid(errors); var result = await _repo.CreateAsync(Request.RequireTenant(), name, kind, def, ui, Request.UserIdOrEmpty(), ct); if (result.Status == WorkflowWriteStatus.Duplicate) throw new ApiException(409, "Workflow name already exists"); SetTag(result.Workflow!.DraftVersion); return Created($"/api/admin/workflows/{result.Workflow.Id}", WorkflowResponse.From(result.Workflow)); }
    [HttpPut("{id:guid}/draft")]
    public async Task<ActionResult<WorkflowResponse>> Update(Guid id, [FromBody] WorkflowUpsert request, CancellationToken ct)
    { RequireManage(); var existing = await _repo.GetAsync(Request.RequireTenant(), id, ct) ?? throw Missing(id); var (def, ui) = Canonical(request); var errors = WorkflowCanonicalizer.ValidateEnvelope(existing.Kind, def, ui); if (errors.Count > 0) throw Invalid(errors); var r = await _repo.UpdateDraftAsync(Request.RequireTenant(), id, Version(), Require(request.Name, "name"), def, ui, ct); return r.Status switch { WorkflowWriteStatus.SystemOwned => throw new ApiException(403, "System-owned Workflow is immutable"), WorkflowWriteStatus.VersionConflict => throw Conflict(), WorkflowWriteStatus.NotFound => throw Missing(id), _ => WithTag(r.Workflow!) }; }
    [HttpPost("{id:guid}/validate")]
    public async Task<ActionResult<WorkflowValidationResponse>> Validate(Guid id, CancellationToken ct)
    { RequireManage(); var tenant = Request.RequireTenant(); var version = Version(); var w = await _repo.GetAsync(tenant, id, ct) ?? throw Missing(id); if (w.SystemOwned) throw new ApiException(403, "System-owned Workflow is immutable"); if (w.DraftVersion != version) throw Conflict(); var local = WorkflowCanonicalizer.ValidateEnvelope(w.Kind, w.DraftDefinition, w.DraftUiMetadata); if (local.Count > 0) { SetTag(version); return Ok(new WorkflowValidationResponse(false, null, null, local)); } var validated = await _compiler.ValidateAsync(w.Kind, w.DraftDefinition, w.DraftUiMetadata, tenant, ct); if (validated.Valid && !await _repo.MarkValidatedAsync(tenant, id, version, validated.CanonicalDefinition, validated.CanonicalUiMetadata, ct)) throw Conflict(); SetTag(version); return Ok(new WorkflowValidationResponse(validated.Valid, Json(validated.CanonicalDefinition), Json(validated.CanonicalUiMetadata), validated.Errors)); }
    [HttpPost("{id:guid}/simulate")]
    public async Task<IActionResult> Simulate(Guid id, CancellationToken ct)
    { RequireManage(); var tenant = Request.RequireTenant(); var w = await _repo.GetAsync(tenant, id, ct) ?? throw Missing(id); var local = WorkflowCanonicalizer.ValidateEnvelope(w.Kind, w.DraftDefinition, w.DraftUiMetadata); if (local.Count > 0) throw Invalid(local); return Ok(await _compiler.SimulateAsync(w.Kind, w.DraftDefinition, w.DraftUiMetadata, tenant, ct)); }
    [HttpPost("{id:guid}/publish")]
    public async Task<ActionResult<WorkflowResponse>> Publish(Guid id, [FromBody] WorkflowPublishRequest request, CancellationToken ct)
    { RequireManage(); var tenant = Request.RequireTenant(); var expected = Version(); if (request.ExpectedDraftVersion != expected) throw new ApiException(400, "If-Match and expected_draft_version must match"); var w = await _repo.GetAsync(tenant, id, ct) ?? throw Missing(id); if (w.DraftVersion != expected || w.DraftValidatedVersion != expected) throw Conflict(); var v = await _compiler.ValidateAsync(w.Kind, w.DraftDefinition, w.DraftUiMetadata, tenant, ct); if (!v.Valid) throw Invalid(v.Errors); var r = await _repo.PublishAsync(tenant, id, expected, v.CanonicalDefinition, v.CanonicalUiMetadata, v.CompilerContractVersion, Request.UserIdOrEmpty(), ct); if (r.Status == WorkflowWriteStatus.VersionConflict) throw Conflict(); if (r.Status == WorkflowWriteStatus.SystemOwned) throw new ApiException(403, "System-owned Workflow is immutable"); return WithTag(r.Workflow!); }
    [HttpGet("{id:guid}/revisions")] public async Task<ActionResult<IReadOnlyList<WorkflowRevisionInfo>>> Revisions(Guid id, CancellationToken ct) { RequireManage(); var tenant = Request.RequireTenant(); if (await _repo.GetAsync(tenant, id, ct) is null) throw Missing(id); return Ok(await _repo.ListRevisionsAsync(tenant, id, ct)); }
    [HttpPost("{id:guid}/revisions/{revision:int}/restore")]
    public async Task<ActionResult<WorkflowResponse>> Restore(Guid id, int revision, CancellationToken ct)
    { RequireManage(); var tenant = Request.RequireTenant(); var w = await _repo.GetAsync(tenant, id, ct) ?? throw Missing(id); var source = await _repo.GetRevisionAsync(tenant, id, revision, ct) ?? throw Missing(id); var v = await _compiler.ValidateAsync(w.Kind, source.Definition, source.UiMetadata, tenant, ct); if (!v.Valid) throw Invalid(v.Errors); var r = await _repo.RestoreAsync(tenant, id, revision, v.CanonicalDefinition, v.CanonicalUiMetadata, v.CompilerContractVersion, Request.UserIdOrEmpty(), ct); if (r.Status == WorkflowWriteStatus.SystemOwned) throw new ApiException(403, "System-owned Workflow is immutable"); return WithTag(r.Workflow!); }
    [HttpDelete("{id:guid}")] public async Task<IActionResult> Disable(Guid id, CancellationToken ct) { RequireManage(); if (!await _repo.SetEnabledAsync(Request.RequireTenant(), id, false, ct)) throw Missing(id); return NoContent(); }
    [HttpPost("{id:guid}/enable")] public async Task<ActionResult<WorkflowResponse>> Enable(Guid id, CancellationToken ct) { RequireManage(); var tenant = Request.RequireTenant(); if (!await _repo.SetEnabledAsync(tenant, id, true, ct)) throw Missing(id); return WithTag((await _repo.GetAsync(tenant, id, ct))!); }
    private void RequireManage() { if (!Request.HasCapability("workflow.manage")) throw new ApiException(403, "workflow.manage capability is required"); }
    private long Version() { var raw = Request.Headers.IfMatch.ToString(); if (string.IsNullOrWhiteSpace(raw)) throw new ApiException(428, "If-Match is required"); if (!long.TryParse(raw.Trim().Trim('\"'), out var v)) throw new ApiException(400, "Invalid If-Match"); return v; }
    private ActionResult<WorkflowResponse> WithTag(Workflow w) { SetTag(w.DraftVersion); return Ok(WorkflowResponse.From(w)); }
    private void SetTag(long v) => Response.Headers.ETag = $"\"{v}\""; private static string Require(string? v, string field) => !string.IsNullOrWhiteSpace(v) ? v.Trim() : throw new ApiException(400, $"{field} is required"); private static (string, string) Canonical(WorkflowUpsert x) => (WorkflowCanonicalizer.Canonicalize(x.Definition), WorkflowCanonicalizer.Canonicalize(x.UiMetadata)); private static System.Text.Json.JsonElement Json(string text) => System.Text.Json.JsonDocument.Parse(text).RootElement.Clone(); private static ApiException Missing(Guid id) => ApiErrors.NotFound(" Workflow", id); private new static ApiException Conflict() => new(409, "Workflow draft has changed or was not validated"); private static ApiException Invalid(IReadOnlyList<WorkflowValidationError> e) => new ApiException(422, "Workflow validation failed") { FieldErrors = e.GroupBy(x => x.Field).ToDictionary(x => x.Key, x => x.First().Message) };
}
