using Dapper;
using Npgsql;

namespace Backend.Api.Workflows;

/// <summary>Dapper source of truth for tenant Workflow drafts and immutable revisions.</summary>
public sealed class WorkflowRepository : IWorkflowRepository
{
    private readonly NpgsqlDataSource _dataSource;
    public WorkflowRepository(NpgsqlDataSource dataSource) => _dataSource = dataSource;

    // Publish 與 Restore 寫的是同一份 revision(supersede 舊的 → 插入新的 → 推進 published_revision)。
    // 唯一差異是 Publish 另外清掉 draft_validated_version(草稿的驗證已被這次發布消耗掉),
    // Restore 不動草稿狀態。兩者用同一個常數串接,送到 Dapper 的 SQL 字元與拆分前完全相同。
    private const string WriteRevisionSql =
        "UPDATE workflow_revision SET status='superseded' WHERE workflow_id=@id AND status='published';"
        + " INSERT INTO workflow_revision(workflow_id,revision,status,schema_version,definition,ui_metadata,definition_canonical,ui_metadata_canonical,definition_sha256,ui_metadata_sha256,compiler_contract_version,created_by)"
        + " VALUES (@id,@next,'published',(CAST(@definition AS jsonb)->>'schemaVersion')::int,@definition::jsonb,@uiMetadata::jsonb,convert_to(@definition,'UTF8'),convert_to(@uiMetadata,'UTF8'),@definitionSha,@uiSha,@contract,@createdBy);"
        + " UPDATE workflow SET published_revision=@next,";
    private const string PublishRevisionSql = WriteRevisionSql + "draft_validated_version=NULL,updated_at=now() WHERE id=@id";
    private const string RestoreRevisionSql = WriteRevisionSql + "updated_at=now() WHERE id=@id";

    public async Task<IReadOnlyList<WorkflowInfo>> ListAsync(string tenantId, CancellationToken ct)
    { await using var c = await _dataSource.OpenConnectionAsync(ct); return (await c.QueryAsync<WorkflowInfo>(new CommandDefinition("SELECT id Id,name Name,kind Kind,enabled Enabled,draft_version DraftVersion,draft_validated_version DraftValidatedVersion,published_revision PublishedRevision,created_at CreatedAt,updated_at UpdatedAt,system_owned SystemOwned FROM workflow WHERE tenant_id=@tenantId ORDER BY name", new { tenantId }, cancellationToken: ct))).AsList(); }
    public async Task<Workflow?> GetAsync(string tenantId, Guid id, CancellationToken ct)
    { await using var c = await _dataSource.OpenConnectionAsync(ct); var row = await c.QuerySingleOrDefaultAsync<Row>(new CommandDefinition("SELECT id Id,name Name,kind Kind,enabled Enabled,draft_version DraftVersion,draft_validated_version DraftValidatedVersion,published_revision PublishedRevision,draft_definition_canonical Definition,draft_ui_metadata_canonical UiMetadata,draft_definition_sha256 DefinitionSha,draft_ui_metadata_sha256 UiSha,created_at CreatedAt,updated_at UpdatedAt,system_owned SystemOwned FROM workflow WHERE tenant_id=@tenantId AND id=@id", new { tenantId, id }, cancellationToken: ct)); return row?.Model(); }
    public async Task<WorkflowWriteResult> CreateAsync(string tenantId, string name, string kind, string definition, string uiMetadata, string createdBy, CancellationToken ct)
    { await using var c = await _dataSource.OpenConnectionAsync(ct); var row = await c.QuerySingleOrDefaultAsync<Row>(new CommandDefinition("INSERT INTO workflow (tenant_id,name,kind,enabled,draft_version,draft_definition,draft_ui_metadata,draft_definition_canonical,draft_ui_metadata_canonical,draft_definition_sha256,draft_ui_metadata_sha256,created_by) VALUES (@tenantId,@name,@kind,true,1,@definition::jsonb,@uiMetadata::jsonb,convert_to(@definition,'UTF8'),convert_to(@uiMetadata,'UTF8'),@definitionSha,@uiSha,@createdBy) ON CONFLICT (tenant_id,name) DO NOTHING RETURNING id Id,name Name,kind Kind,enabled Enabled,draft_version DraftVersion,draft_validated_version DraftValidatedVersion,published_revision PublishedRevision,draft_definition_canonical Definition,draft_ui_metadata_canonical UiMetadata,draft_definition_sha256 DefinitionSha,draft_ui_metadata_sha256 UiSha,created_at CreatedAt,updated_at UpdatedAt,system_owned SystemOwned", new { tenantId, name, kind, definition, uiMetadata, definitionSha = WorkflowCanonicalizer.Hash(definition), uiSha = WorkflowCanonicalizer.Hash(uiMetadata), createdBy }, cancellationToken: ct)); return row is null ? new(WorkflowWriteStatus.Duplicate) : new(WorkflowWriteStatus.Success, row.Model()); }
    public async Task<WorkflowWriteResult> UpdateDraftAsync(string tenantId, Guid id, long expected, string name, string definition, string uiMetadata, CancellationToken ct)
    { await using var c = await _dataSource.OpenConnectionAsync(ct); var row = await c.QuerySingleOrDefaultAsync<Row>(new CommandDefinition("UPDATE workflow SET name=@name,draft_definition=@definition::jsonb,draft_ui_metadata=@uiMetadata::jsonb,draft_definition_canonical=convert_to(@definition,'UTF8'),draft_ui_metadata_canonical=convert_to(@uiMetadata,'UTF8'),draft_definition_sha256=@definitionSha,draft_ui_metadata_sha256=@uiSha,draft_version=draft_version+1,draft_validated_version=NULL,updated_at=now() WHERE tenant_id=@tenantId AND id=@id AND draft_version=@expected AND NOT system_owned RETURNING id Id,name Name,kind Kind,enabled Enabled,draft_version DraftVersion,draft_validated_version DraftValidatedVersion,published_revision PublishedRevision,draft_definition_canonical Definition,draft_ui_metadata_canonical UiMetadata,draft_definition_sha256 DefinitionSha,draft_ui_metadata_sha256 UiSha,created_at CreatedAt,updated_at UpdatedAt,system_owned SystemOwned", new { tenantId, id, expected, name, definition, uiMetadata, definitionSha = WorkflowCanonicalizer.Hash(definition), uiSha = WorkflowCanonicalizer.Hash(uiMetadata) }, cancellationToken: ct)); if (row is not null) return new(WorkflowWriteStatus.Success, row.Model()); var current = await c.ExecuteScalarAsync<long?>(new CommandDefinition("SELECT draft_version FROM workflow WHERE tenant_id=@tenantId AND id=@id", new { tenantId, id }, cancellationToken: ct)); return current is long version ? new(WorkflowWriteStatus.VersionConflict, CurrentDraftVersion: version) : new(WorkflowWriteStatus.NotFound); }
    public async Task<bool> MarkValidatedAsync(string tenantId, Guid id, long version, string definition, string uiMetadata, CancellationToken ct)
    { await using var c = await _dataSource.OpenConnectionAsync(ct); return await c.ExecuteAsync(new CommandDefinition("UPDATE workflow SET draft_definition=@definition::jsonb,draft_ui_metadata=@uiMetadata::jsonb,draft_definition_canonical=convert_to(@definition,'UTF8'),draft_ui_metadata_canonical=convert_to(@uiMetadata,'UTF8'),draft_definition_sha256=@definitionSha,draft_ui_metadata_sha256=@uiSha,draft_validated_version=@version,updated_at=now() WHERE tenant_id=@tenantId AND id=@id AND draft_version=@version AND NOT system_owned", new { tenantId, id, version, definition, uiMetadata, definitionSha = WorkflowCanonicalizer.Hash(definition), uiSha = WorkflowCanonicalizer.Hash(uiMetadata) }, cancellationToken: ct)) == 1; }
    public async Task<WorkflowWriteResult> PublishAsync(string tenantId, Guid id, long expected, string definition, string uiMetadata, string contract, string createdBy, CancellationToken ct)
    { await using var c = await _dataSource.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); var state = await c.QuerySingleOrDefaultAsync<State>(new CommandDefinition("SELECT draft_version DraftVersion,draft_validated_version Validated,published_revision Published,system_owned SystemOwned,draft_definition_canonical Definition,draft_ui_metadata_canonical UiMetadata FROM workflow WHERE tenant_id=@tenantId AND id=@id FOR UPDATE", new { tenantId, id }, tx, cancellationToken: ct)); if (state is null) return new(WorkflowWriteStatus.NotFound); if (state.SystemOwned) return new(WorkflowWriteStatus.SystemOwned); if (state.DraftVersion != expected || state.Validated != expected || state.DefinitionText() != definition || state.UiText() != uiMetadata) return new(WorkflowWriteStatus.VersionConflict); var next = (state.Published ?? 0) + 1; await c.ExecuteAsync(new CommandDefinition(PublishRevisionSql, new { id, next, definition, uiMetadata, definitionSha = WorkflowCanonicalizer.Hash(definition), uiSha = WorkflowCanonicalizer.Hash(uiMetadata), contract, createdBy }, tx, cancellationToken: ct)); await tx.CommitAsync(ct); return new(WorkflowWriteStatus.Success, await GetAsync(tenantId, id, ct), next); }
    public async Task<IReadOnlyList<WorkflowRevisionInfo>> ListRevisionsAsync(string tenantId, Guid id, CancellationToken ct) { await using var c = await _dataSource.OpenConnectionAsync(ct); return (await c.QueryAsync<WorkflowRevisionInfo>(new CommandDefinition("SELECT r.revision Revision,r.status Status,r.definition_sha256 DefinitionSha256,r.ui_metadata_sha256 UiMetadataSha256,r.compiler_contract_version CompilerContractVersion,r.created_by CreatedBy,r.created_at CreatedAt FROM workflow_revision r JOIN workflow w ON w.id=r.workflow_id WHERE w.tenant_id=@tenantId AND w.id=@id ORDER BY r.revision DESC", new { tenantId, id }, cancellationToken: ct))).AsList(); }
    public async Task<(string Definition, string UiMetadata)?> GetRevisionAsync(string tenantId, Guid id, int revision, CancellationToken ct) { await using var c = await _dataSource.OpenConnectionAsync(ct); var r = await c.QuerySingleOrDefaultAsync<Revision>(new CommandDefinition("SELECT definition_canonical Definition,ui_metadata_canonical UiMetadata FROM workflow_revision r JOIN workflow w ON w.id=r.workflow_id WHERE w.tenant_id=@tenantId AND w.id=@id AND r.revision=@revision", new { tenantId, id, revision }, cancellationToken: ct)); return r is null ? null : (r.DefinitionText(), r.UiText()); }
    public async Task<WorkflowWriteResult> RestoreAsync(string tenantId, Guid id, int revision, string definition, string uiMetadata, string contract, string createdBy, CancellationToken ct) { await using var c = await _dataSource.OpenConnectionAsync(ct); if (!await c.ExecuteScalarAsync<bool>(new CommandDefinition("SELECT EXISTS(SELECT 1 FROM workflow_revision r JOIN workflow w ON w.id=r.workflow_id WHERE w.tenant_id=@tenantId AND w.id=@id AND r.revision=@revision)", new { tenantId, id, revision }, cancellationToken: ct))) return new(WorkflowWriteStatus.NotFound); await using var tx = await c.BeginTransactionAsync(ct); var state = await c.QuerySingleOrDefaultAsync<State>(new CommandDefinition("SELECT published_revision Published,system_owned SystemOwned FROM workflow WHERE tenant_id=@tenantId AND id=@id FOR UPDATE", new { tenantId, id }, tx, cancellationToken: ct)); if (state is null) return new(WorkflowWriteStatus.NotFound); if (state.SystemOwned) return new(WorkflowWriteStatus.SystemOwned); var next = (state.Published ?? 0) + 1; await c.ExecuteAsync(new CommandDefinition(RestoreRevisionSql, new { id, next, definition, uiMetadata, definitionSha = WorkflowCanonicalizer.Hash(definition), uiSha = WorkflowCanonicalizer.Hash(uiMetadata), contract, createdBy }, tx, cancellationToken: ct)); await tx.CommitAsync(ct); return new(WorkflowWriteStatus.Success, await GetAsync(tenantId, id, ct), next); }
    public async Task<bool> SetEnabledAsync(string tenantId, Guid id, bool enabled, CancellationToken ct) { await using var c = await _dataSource.OpenConnectionAsync(ct); return await c.ExecuteAsync(new CommandDefinition("UPDATE workflow SET enabled=@enabled,updated_at=now() WHERE tenant_id=@tenantId AND id=@id AND NOT system_owned", new { tenantId, id, enabled }, cancellationToken: ct)) == 1; }
    private sealed record Row(Guid Id, string Name, string Kind, bool Enabled, long DraftVersion, long? DraftValidatedVersion, int? PublishedRevision, byte[] Definition, byte[] UiMetadata, string DefinitionSha, string UiSha, DateTime CreatedAt, DateTime UpdatedAt, bool SystemOwned) { public Workflow Model() => new(Id, Name, Kind, Enabled, DraftVersion, DraftValidatedVersion, PublishedRevision, System.Text.Encoding.UTF8.GetString(Definition), System.Text.Encoding.UTF8.GetString(UiMetadata), DefinitionSha, UiSha, CreatedAt, UpdatedAt, SystemOwned); }
    private sealed record State(long DraftVersion, long? Validated, int? Published, bool SystemOwned, byte[]? Definition = null, byte[]? UiMetadata = null) { public string DefinitionText() => System.Text.Encoding.UTF8.GetString(Definition ?? []); public string UiText() => System.Text.Encoding.UTF8.GetString(UiMetadata ?? []); }
    private sealed record Revision(byte[] Definition, byte[] UiMetadata) { public string DefinitionText() => System.Text.Encoding.UTF8.GetString(Definition); public string UiText() => System.Text.Encoding.UTF8.GetString(UiMetadata); }
}
