using Backend.Api.Agents;
using System.Text;

namespace Backend.Api.Common;

/// <summary>
/// 解析呼叫者經 header 轉發的身分:X-Tenant-Id(租戶 code)、X-User-Id(username)、X-User-Role。
/// backend 不自行驗 JWT,身分由已通過內部憑證的上游(platform/workflow)如實轉發。
/// </summary>
public static class IdentityHeaders
{
    public const string TenantHeader = "X-Tenant-Id";
    public const string UserHeader = "X-User-Id";
    public const string RoleHeader = "X-User-Role";
    public const string CapabilitiesHeader = "X-User-Capabilities";
    public const string GroupsHeader = "X-User-Groups";

    public static string? UserId(this HttpRequest request) => Value(request, UserHeader);

    /// <summary>UserId 缺標頭時的空字串回落(寫入用途:AddedBy/CreatedBy 等欄位不接受 null)。</summary>
    public static string UserIdOrEmpty(this HttpRequest request) => Value(request, UserHeader) ?? string.Empty;

    public static string? UserRole(this HttpRequest request) => Value(request, RoleHeader);

    /// <summary>
    /// X-User-Capabilities 的 wire 邊界,與 X-User-Groups 同類的內部 header 上限(數字集中在此處)。
    /// 只限制數量/長度/位元組,刻意不驗 capability 名稱文法:<see cref="RequireCapability"/> 是
    /// Ordinal 精確比對,未知字串本來就命不中任何授權,加文法只會讓未來新增的合法名稱被 400。
    /// </summary>
    public const int MaxCallerCapabilities = 64;

    /// <inheritdoc cref="MaxCallerCapabilities"/>
    public const int MaxCapabilitiesWireUtf8Bytes = 4096;

    /// <inheritdoc cref="MaxCallerCapabilities"/>
    public const int MaxCapabilityLength = 256;

    /// <summary>
    /// Persisted capability claims forwarded from Platform's authenticated JWT. Header values are
    /// space-delimited because individual capability names cannot contain whitespace.
    /// Bounded like <see cref="UserGroups"/>: an absent header is the normal empty-grant path, but
    /// a present header must be exactly one value, at most <see cref="MaxCapabilitiesWireUtf8Bytes"/>
    /// UTF-8 wire bytes, at most <see cref="MaxCallerCapabilities"/> entries, control-char free, and
    /// each entry at most <see cref="MaxCapabilityLength"/> chars. A malformed value rejects the
    /// entire header (400) instead of skipping the offending entry, so no partial capability set can
    /// be used for authorization.
    /// </summary>
    public static IReadOnlyList<string> UserCapabilities(this HttpRequest request)
    {
        var values = request.Headers[CapabilitiesHeader];
        if (values.Count == 0)
        {
            return Array.Empty<string>();
        }

        if (values.Count != 1)
        {
            throw InvalidCapabilitiesHeader();
        }

        var raw = values[0] ?? string.Empty;
        // 控制字元檢查在整串上做(而非逐 entry):TrimEntries 會把「被空白包住的純控制字元 token」
        // 吃成空字串而消失,只查 entry 會漏掉那一類 wire 值。
        if (Encoding.UTF8.GetByteCount(raw) > MaxCapabilitiesWireUtf8Bytes
            || raw.Any(char.IsControl))
        {
            throw InvalidCapabilitiesHeader();
        }

        var capabilities = raw.Split(
            ' ',
            StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (capabilities.Length > MaxCallerCapabilities
            || capabilities.Any(capability => capability.Length > MaxCapabilityLength))
        {
            throw InvalidCapabilitiesHeader();
        }

        return capabilities
            .Distinct(StringComparer.Ordinal)
            .ToArray();
    }

    private static ApiException InvalidCapabilitiesHeader()
        => new(
            StatusCodes.Status400BadRequest,
            "X-User-Capabilities contains an invalid authenticated capability set");

    /// <summary>
    /// 需要具名 capability 的端點:缺該 claim 直接 403。Workflow designer management is intentionally
    /// capability based: a tenant ADMIN is not implicitly a SYSTEM_ADMIN.  The Platform regenerates
    /// this header from repeated signed JWT claims; keep the backend check ordinal/exact and fail
    /// closed when the claim is absent.
    /// </summary>
    public static void RequireCapability(this HttpRequest request, string capability)
    {
        if (!request.UserCapabilities().Contains(capability, StringComparer.Ordinal))
        {
            throw new ApiException(StatusCodes.Status403Forbidden, capability + " capability is required");
        }
    }

    /// <summary>
    /// Authenticated memberships regenerated by Platform from signed JWT claims. The wire
    /// format is space-delimited canonical group ids. A malformed value rejects the entire
    /// header so no partial membership set can grant audience access.
    /// </summary>
    public static IReadOnlyList<string> UserGroups(this HttpRequest request)
    {
        var values = request.Headers[GroupsHeader];
        if (values.Count == 0)
        {
            return Array.Empty<string>();
        }

        if (values.Count != 1)
        {
            throw InvalidGroupsHeader();
        }
        var raw = values[0] ?? string.Empty;
        var groups = raw.Split(' ', StringSplitOptions.None);
        if (groups.Length is < 1 or > AgentAudience.MaxCallerGroups
            || groups.Any(string.IsNullOrEmpty)
            || !AgentAudience.IsCanonicalGroupSet(groups)
            || Encoding.UTF8.GetByteCount(raw)
            > AgentAudience.MaxGroupsWireUtf8Bytes)
        {
            throw InvalidGroupsHeader();
        }

        return groups
            .Distinct(StringComparer.Ordinal)
            .OrderBy(group => group, StringComparer.Ordinal)
            .ToArray();
    }

    private static ApiException InvalidGroupsHeader()
        => new(
            StatusCodes.Status400BadRequest,
            "X-User-Groups contains an invalid authenticated group set");

    /// <summary>需要租戶的端點:缺 X-Tenant-Id 直接 400。</summary>
    public static string RequireTenant(this HttpRequest request) =>
        Value(request, TenantHeader) ?? throw new ApiException(StatusCodes.Status400BadRequest, "缺少租戶識別標頭：X-Tenant-Id");

    /// <summary>需要呼叫者身分的端點:缺 X-User-Id 直接 400。</summary>
    public static string RequireUserId(this HttpRequest request) =>
        Value(request, UserHeader) ?? throw new ApiException(StatusCodes.Status400BadRequest, "X-User-Id is required");

    /// <summary>
    /// 把角色當持久化欄位寫入的端點(D5 <c>caller_role</c> 是 NOT NULL):缺 X-User-Role 直接 400。
    /// 角色「選填、缺則空字串」的既有端點仍用 <see cref="UserRole"/>,語意不同不要混用。
    /// </summary>
    public static string RequireUserRole(this HttpRequest request) =>
        Value(request, RoleHeader) ?? throw new ApiException(StatusCodes.Status400BadRequest, "X-User-Role is required");

    /// <summary>
    /// 不透明內部 header 的共用邊界檢查:恰一個值、trim 後 1..128 字元、無控制字元;不符一律 null。
    /// 「不符時要做什麼」由呼叫端決定(Idempotency-Key → 400;X-Correlation-Id → 當作沒帶)。
    /// 128 是這類內部 token header 的共用上限,不是各自獨立的數字。
    ///
    /// correlation 用途下,這裡只是鏈路上較寬的一段:最終字元集由 workflow 的
    /// <c>_SAFE_ID = [A-Za-z0-9._:-]{1,128}</c> 白名單決定,通過本檢查但含其他字元的值到 workflow
    /// 會被丟棄並改生 uuid(追蹤編號因此在該段斷開,不是錯誤)。不在此收緊:本方法同時是
    /// <see cref="RequireIdempotencyKey"/> 的驗證器,縮字元集會連動改變冪等鍵語意。
    /// </summary>
    public static string? SingleBoundedValue(this HttpRequest request, string name)
    {
        var values = request.Headers[name];
        var value = values.Count == 1 ? values[0]?.Trim() : null;
        return string.IsNullOrWhiteSpace(value) || value.Length > 128 || value.Any(char.IsControl)
            ? null
            : value;
    }

    /// <summary>
    /// Shared idempotent-write header contract (regression-overrides, eval-runs): exactly one
    /// non-blank, control-char-free `Idempotency-Key` header up to 128 chars, or 400.
    /// </summary>
    public static string RequireIdempotencyKey(this HttpRequest request)
        => request.SingleBoundedValue("Idempotency-Key")
           ?? throw new ApiException(StatusCodes.Status400BadRequest, "Idempotency-Key is required");

    private static string? Value(HttpRequest request, string name)
    {
        var v = request.Headers[name].ToString();
        return string.IsNullOrWhiteSpace(v) ? null : v;
    }
}
