using Backend.Api.Agents;
using System.Text;

namespace Backend.Api.Common;

/// <summary>
/// 解析呼叫者經 header 轉發的身分:X-Tenant-Id(租戶 code)、X-User-Id(username)、X-User-Role。
/// backend 不自行驗 JWT,身分由已通過內部憑證的上游(platform/workflow)如實轉發。
/// </summary>
public static class IdentityHeaders
{
    public const string TenantHeader = "X-Tenant-Id";
    public const string UserHeader = "X-User-Id";
    public const string RoleHeader = "X-User-Role";
    public const string CapabilitiesHeader = "X-User-Capabilities";
    public const string GroupsHeader = "X-User-Groups";

    public static string? UserId(this HttpRequest request) => Value(request, UserHeader);

    /// <summary>UserId 缺標頭時的空字串回落(寫入用途:AddedBy/CreatedBy 等欄位不接受 null)。</summary>
    public static string UserIdOrEmpty(this HttpRequest request) => Value(request, UserHeader) ?? string.Empty;

    public static string? UserRole(this HttpRequest request) => Value(request, RoleHeader);

    /// <summary>
    /// Persisted capability claims forwarded from Platform's authenticated JWT. Header values are
    /// space-delimited because individual capability names cannot contain whitespace.
    /// </summary>
    public static IReadOnlyList<string> UserCapabilities(this HttpRequest request)
        => request.Headers[CapabilitiesHeader]
            .SelectMany(value => (value ?? string.Empty).Split(
                ' ',
                StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            .Distinct(StringComparer.Ordinal)
            .ToArray();

    /// <summary>
    /// 需要具名 capability 的端點:缺該 claim 直接 403。Workflow designer management is intentionally
    /// capability based: a tenant ADMIN is not implicitly a SYSTEM_ADMIN.  The Platform regenerates
    /// this header from repeated signed JWT claims; keep the backend check ordinal/exact and fail
    /// closed when the claim is absent.
    /// </summary>
    public static void RequireCapability(this HttpRequest request, string capability)
    {
        if (!request.UserCapabilities().Contains(capability, StringComparer.Ordinal))
        {
            throw new ApiException(StatusCodes.Status403Forbidden, capability + " capability is required");
        }
    }

    /// <summary>
    /// Authenticated memberships regenerated by Platform from signed JWT claims. The wire
    /// format is space-delimited canonical group ids. A malformed value rejects the entire
    /// header so no partial membership set can grant audience access.
    /// </summary>
    public static IReadOnlyList<string> UserGroups(this HttpRequest request)
    {
        var values = request.Headers[GroupsHeader];
        if (values.Count == 0)
        {
            return Array.Empty<string>();
        }

        if (values.Count != 1)
        {
            throw InvalidGroupsHeader();
        }
        var raw = values[0] ?? string.Empty;
        var groups = raw.Split(' ', StringSplitOptions.None);
        if (groups.Length is < 1 or > AgentAudience.MaxCallerGroups
            || groups.Any(string.IsNullOrEmpty)
            || !AgentAudience.IsCanonicalGroupSet(groups)
            || Encoding.UTF8.GetByteCount(raw)
            > AgentAudience.MaxGroupsWireUtf8Bytes)
        {
            throw InvalidGroupsHeader();
        }

        return groups
            .Distinct(StringComparer.Ordinal)
            .OrderBy(group => group, StringComparer.Ordinal)
            .ToArray();
    }

    private static ApiException InvalidGroupsHeader()
        => new(
            StatusCodes.Status400BadRequest,
            "X-User-Groups contains an invalid authenticated group set");

    /// <summary>需要租戶的端點:缺 X-Tenant-Id 直接 400。</summary>
    public static string RequireTenant(this HttpRequest request) =>
        Value(request, TenantHeader) ?? throw new ApiException(StatusCodes.Status400BadRequest, "缺少租戶識別標頭：X-Tenant-Id");

    /// <summary>需要呼叫者身分的端點:缺 X-User-Id 直接 400。</summary>
    public static string RequireUserId(this HttpRequest request) =>
        Value(request, UserHeader) ?? throw new ApiException(StatusCodes.Status400BadRequest, "X-User-Id is required");

    /// <summary>
    /// Shared idempotent-write header contract (regression-overrides, eval-runs): exactly one
    /// non-blank, control-char-free `Idempotency-Key` header up to 128 chars, or 400.
    /// </summary>
    public static string RequireIdempotencyKey(this HttpRequest request)
    {
        var values = request.Headers["Idempotency-Key"];
        var key = values.Count == 1 ? values[0]?.Trim() : null;
        if (string.IsNullOrWhiteSpace(key) || key.Length > 128 || key.Any(char.IsControl))
        {
            throw new ApiException(StatusCodes.Status400BadRequest, "Idempotency-Key is required");
        }
        return key;
    }

    private static string? Value(HttpRequest request, string name)
    {
        var v = request.Headers[name].ToString();
        return string.IsNullOrWhiteSpace(v) ? null : v;
    }
}
