using System.Text;
using System.Text.Json.Nodes;
using Backend.Api.Agents;
using Backend.Api.Data;
using Backend.Api.Orchestrators;
using Backend.Api.Workflows;
using Dapper;
using Microsoft.Extensions.Logging.Abstractions;

namespace Backend.Api.Tests;

[Collection("Postgres")]
public sealed class OrchestratorRepositoryTests(PostgresFixture fixture)
{
    [SkippableFact]
    public async Task Publish_PinsAndPersistsExactCanonicalReferences()
    {
        fixture.SkipIfUnavailable(); await DbBootstrap.RunAsync(fixture.DataSource!, NullLogger.Instance); var tenant = "orchestratorrepo-" + Guid.NewGuid().ToString("N"); var wid = Guid.NewGuid(); var verifierWorkflow = Guid.NewGuid(); var verifier = Guid.NewGuid(); var worker = Guid.NewGuid(); var agentDef = """{"allowed_tools":[],"audience":[],"business_rules":{},"capabilities":[],"execution_roles":["ROLE"],"knowledge_sources":[],"output_contract":{},"runtime_limits":{},"runtime_workflow":{"id":"WORKFLOW","revision":REVISION},"skill_bindings":[],"system_prompt":"test"}""";
        var emptyHash = Backend.Api.Skills.SkillHash.Sha256("{}"); await using var c = await fixture.DataSource!.OpenConnectionAsync(); await c.ExecuteAsync("INSERT INTO workflow(id,tenant_id,name,kind,enabled,draft_definition,draft_ui_metadata,draft_definition_canonical,draft_ui_metadata_canonical,draft_definition_sha256,draft_ui_metadata_sha256,published_revision) VALUES(@wid,@tenant,'Root','orchestrator',true,'{}','{}',convert_to('{}','UTF8'),convert_to('{}','UTF8'),@emptyHash,@emptyHash,1); INSERT INTO workflow_revision(workflow_id,revision,status,definition,ui_metadata,definition_canonical,ui_metadata_canonical,definition_sha256,ui_metadata_sha256) VALUES(@wid,1,'published','{}','{}',convert_to('{}','UTF8'),convert_to('{}','UTF8'),@emptyHash,@emptyHash);", new { wid, tenant, emptyHash });
        var verifierGraph = VerifierGraph(); var verifierGraphHash = Backend.Api.Skills.SkillHash.Sha256(verifierGraph); await c.ExecuteAsync("INSERT INTO workflow(id,tenant_id,name,kind,enabled,draft_definition,draft_ui_metadata,draft_definition_canonical,draft_ui_metadata_canonical,draft_definition_sha256,draft_ui_metadata_sha256,published_revision) VALUES(@verifierWorkflow,@tenant,'Verifier Runtime','agent-runtime',true,@verifierGraph::jsonb,'{}',convert_to(@verifierGraph,'UTF8'),convert_to('{}','UTF8'),@verifierGraphHash,@emptyHash,1); INSERT INTO workflow_revision(workflow_id,revision,status,definition,ui_metadata,definition_canonical,ui_metadata_canonical,definition_sha256,ui_metadata_sha256,compiler_contract_version) VALUES(@verifierWorkflow,1,'published',@verifierGraph::jsonb,'{}',convert_to(@verifierGraph,'UTF8'),convert_to('{}','UTF8'),@verifierGraphHash,@emptyHash,@contract);", new { verifierWorkflow, tenant, verifierGraph, verifierGraphHash, emptyHash, contract = OrchestratorReferencePolicy.SupportedCompilerContract });
        foreach (var pair in new[] { (verifier, "verifier"), (worker, "worker") }) { var runtimeId = pair.Item2 == "verifier" ? verifierWorkflow : Guid.Parse(Backend.Api.Agents.AgentDefaults.RuntimeWorkflowId); var runtimeRevision = pair.Item2 == "verifier" ? 1 : Backend.Api.Agents.AgentDefaults.RuntimeWorkflowRevision; var text = agentDef.Replace("ROLE", pair.Item2).Replace("WORKFLOW", runtimeId.ToString("D")).Replace("REVISION", runtimeRevision.ToString()); if (pair.Item2 == "verifier") text = text.Replace("\"output_contract\":{}", "\"output_contract\":{\"type\":\"verification-report\"}"); var bytes = Encoding.UTF8.GetBytes(text); var sha = Backend.Api.Skills.SkillHash.Sha256(text); await c.ExecuteAsync("INSERT INTO agent(id,tenant_id,slug,name,draft_definition,draft_definition_canonical,draft_definition_sha256,published_revision) VALUES(@id,@tenant,@slug,@slug,'{}',convert_to('{}','UTF8'),'x',1); INSERT INTO agent_revision(agent_id,revision,status,canonical_definition,definition_sha256,runtime_workflow_id,runtime_workflow_revision) VALUES(@id,1,'published',@bytes,@sha,@runtimeId,@runtimeRevision);", new { id = pair.Item1, tenant, slug = pair.Item2, bytes, sha, runtimeId, runtimeRevision }); }
        var definition = $$$"""{"instructions":"coordinate","policy":{"dispatchMode":"bounded-parallel","joinPolicy":"repair","repairPolicy":"redispatch","aggregationPolicy":"verified-only","denialPolicy":"fail-closed"},"audience":[],"budgets":{"maxChildRuns":3,"maxConcurrency":1,"maxContextRounds":1,"maxRepairRounds":1,"maxTasks":2,"timeoutSeconds":60,"tokenBudget":1000},"capabilities":[],"context":{"allowedTools":[],"knowledgeSources":[],"readOnly":true},"verifier":{"agentId":"{{{verifier:D}}}","independent":true,"outputContract":{"type":"verification-report"},"revision":1,"variant":"read-only"},"workerPool":[{"agentId":"{{{worker:D}}}","revision":1}],"workerPolicy":{"requiredAudience":[],"requiredCapabilities":[],"selection":"pinned-only"},"workflow":{"id":"{{{wid:D}}}","revision":1}}"""; definition = OrchestratorCanonicalizer.Canonicalize(definition); var repo = new OrchestratorRepository(fixture.DataSource!); await c.ExecuteAsync("UPDATE agent_revision SET runtime_workflow_id=@wrong,runtime_workflow_revision=@wrongRevision WHERE agent_id=@verifier AND revision=1", new { wrong = Guid.Parse(AgentDefaults.RuntimeWorkflowId), wrongRevision = AgentDefaults.RuntimeWorkflowRevision, verifier }); Assert.Contains(await repo.ValidateReferencesAsync(tenant, definition, default), x => x.Contains("does not match immutable revision projection")); await c.ExecuteAsync("UPDATE agent_revision SET runtime_workflow_id=@verifierWorkflow,runtime_workflow_revision=1 WHERE agent_id=@verifier AND revision=1", new { verifierWorkflow, verifier }); var created = await repo.CreateAsync(tenant, "Root", "", definition, "admin", default); Assert.True(await repo.MarkValidatedAsync(tenant, created.Orchestrator!.Id, 1, definition, default)); var published = await repo.PublishAsync(tenant, created.Orchestrator.Id, 1, definition, "admin", default); Assert.Equal(OrchestratorWriteStatus.Success, published.Status); var bytesStored = await c.ExecuteScalarAsync<byte[]>("SELECT canonical_definition FROM orchestrator_revision WHERE orchestrator_id=@id", new { id = created.Orchestrator.Id }); Assert.Equal(Encoding.UTF8.GetBytes(definition), bytesStored);
    }
    [SkippableFact] public async Task SystemOwnedWorkflow_RejectsMarkValidated() { fixture.SkipIfUnavailable(); await DbBootstrap.RunAsync(fixture.DataSource!, NullLogger.Instance); var repo = new WorkflowRepository(fixture.DataSource!); Assert.False(await repo.MarkValidatedAsync(Backend.Api.Agents.AgentDefaults.SystemTenant, Guid.Parse(Backend.Api.Agents.AgentDefaults.RuntimeWorkflowId), 1, Backend.Api.Agents.AgentDefaults.RuntimeWorkflowDefinition, "{}", default)); }
    [SkippableFact] public async Task Preflight_RejectsCorruptPublishedWorkflowHash() { fixture.SkipIfUnavailable(); await DbBootstrap.RunAsync(fixture.DataSource!, NullLogger.Instance); var tenant = "orchestrator-corrupt-" + Guid.NewGuid().ToString("N"); var wid = Guid.NewGuid(); await using var c = await fixture.DataSource!.OpenConnectionAsync(); await c.ExecuteAsync("INSERT INTO workflow(id,tenant_id,name,kind,enabled,draft_definition,draft_ui_metadata,draft_definition_canonical,draft_ui_metadata_canonical,draft_definition_sha256,draft_ui_metadata_sha256,published_revision) VALUES(@wid,@tenant,'Corrupt','orchestrator',true,'{}','{}',convert_to('{}','UTF8'),convert_to('{}','UTF8'),'bad','bad',1); INSERT INTO workflow_revision(workflow_id,revision,status,definition,ui_metadata,definition_canonical,ui_metadata_canonical,definition_sha256,ui_metadata_sha256) VALUES(@wid,1,'published','{}','{}',convert_to('{}','UTF8'),convert_to('{}','UTF8'),'bad','bad');", new { wid, tenant }); var verifier = Guid.NewGuid(); var worker = Guid.NewGuid(); var definition = $$$"""{"instructions":"root","policy":{"dispatchMode":"bounded-parallel","joinPolicy":"repair","repairPolicy":"redispatch","aggregationPolicy":"verified-only","denialPolicy":"fail-closed"},"workflow":{"id":"{{{wid:D}}}","revision":1},"verifier":{"agentId":"{{{verifier:D}}}","revision":1,"variant":"read-only","independent":true,"outputContract":{"type":"verification-report"}},"workerPool":[{"agentId":"{{{worker:D}}}","revision":1}],"workerPolicy":{"requiredAudience":[],"requiredCapabilities":[],"selection":"pinned-only"},"context":{"readOnly":true,"allowedTools":[],"knowledgeSources":[]},"audience":[],"capabilities":[],"budgets":{"maxContextRounds":1,"maxTasks":1,"maxChildRuns":2,"maxConcurrency":1,"maxRepairRounds":1,"tokenBudget":1,"timeoutSeconds":1}}"""; var errors = await new OrchestratorRepository(fixture.DataSource!).ValidateReferencesAsync(tenant, definition, default); Assert.Contains(errors, x => x.Contains("integrity")); }
    [Fact] public void VerifierWorkflowGuard_RejectsLegacyWorkerAndSemanticInvalid() { Assert.Contains(OrchestratorReferencePolicy.ValidateVerifierWorkflowDefinition(VerifierGraph(), "1"), x => x.Contains("compiler contract")); Assert.Contains(OrchestratorReferencePolicy.ValidateVerifierWorkflowDefinition(AgentDefaults.RuntimeWorkflowDefinition, OrchestratorReferencePolicy.SupportedCompilerContract), x => x.Contains("runtimeVariant") || x.Contains("forbidden")); var broken = VerifierGraph().Replace("\"maxSteps\":40", "\"maxSteps\":0"); Assert.Contains(OrchestratorReferencePolicy.ValidateVerifierWorkflowDefinition(broken, OrchestratorReferencePolicy.SupportedCompilerContract), x => x.Contains("governance")); }
    [Fact] public void AgentRuntimeWorkflowProjection_MustMatchCanonicalBytes() { var id = Guid.NewGuid(); var definition = $$$"""{"runtime_workflow":{"id":"{{{id:D}}}","revision":2}}"""; Assert.Empty(OrchestratorReferencePolicy.ValidateRuntimeWorkflowProjection(definition, id, 2)); Assert.NotEmpty(OrchestratorReferencePolicy.ValidateRuntimeWorkflowProjection(definition, Guid.NewGuid(), 2)); Assert.NotEmpty(OrchestratorReferencePolicy.ValidateRuntimeWorkflowProjection(definition, id, 3)); }
    private static string VerifierGraph() { var root = JsonNode.Parse(AgentDefaults.RuntimeWorkflowDefinition)!.AsObject(); root["runtimeVariant"] = "verifier"; var loop = root["nodes"]!.AsArray().Single(x => x!["type"]!.GetValue<string>() == "bounded_agent_loop")!; var children = loop["children"]!.AsArray(); foreach (var child in children.Where(x => x is not null && new[] { "load_skill", "tool_policy_and_approval_gate", "tool_call_and_observation" }.Contains(x["type"]!.GetValue<string>())).ToArray()) children.Remove(child); return Backend.Api.Agents.AgentCanonicalizer.CanonicalizeDefinition(root.ToJsonString()); }
}
