using System.Text;
using System.Text.Json;
using Dapper;
using Npgsql;
using Backend.Api.Workflows;
using Backend.Api.Skills;

namespace Backend.Api.Orchestrators;

public sealed class OrchestratorRepository(NpgsqlDataSource dataSource) : IOrchestratorRepository
{
    public async Task<IReadOnlyList<OrchestratorInfo>> ListAsync(string tenant, CancellationToken ct) { await using var c = await dataSource.OpenConnectionAsync(ct); return (await c.QueryAsync<OrchestratorInfo>(new CommandDefinition("SELECT id Id,name Name,description Description,enabled Enabled,draft_version DraftVersion,draft_validated_version DraftValidatedVersion,published_revision PublishedRevision,created_at CreatedAt,updated_at UpdatedAt FROM orchestrator WHERE tenant_id=@tenant ORDER BY name", new { tenant }, cancellationToken: ct))).AsList(); }
    public async Task<Orchestrator?> GetAsync(string tenant, Guid id, CancellationToken ct) { await using var c = await dataSource.OpenConnectionAsync(ct); var r = await c.QuerySingleOrDefaultAsync<Row>(new CommandDefinition("SELECT id Id,name Name,description Description,enabled Enabled,draft_version DraftVersion,draft_validated_version DraftValidatedVersion,published_revision PublishedRevision,draft_definition_canonical Definition,created_at CreatedAt,updated_at UpdatedAt FROM orchestrator WHERE tenant_id=@tenant AND id=@id", new { tenant, id }, cancellationToken: ct)); return r?.ToModel(); }
    public async Task<OrchestratorWriteResult> CreateAsync(string tenant, string name, string description, string definition, string by, CancellationToken ct) { await using var c = await dataSource.OpenConnectionAsync(ct); var r = await c.QuerySingleOrDefaultAsync<Row>(new CommandDefinition("INSERT INTO orchestrator(tenant_id,name,description,draft_definition,draft_definition_canonical,draft_definition_sha256,created_by) VALUES(@tenant,@name,@description,@definition::jsonb,convert_to(@definition,'UTF8'),@hash,@by) ON CONFLICT(tenant_id,name) DO NOTHING RETURNING id Id,name Name,description Description,enabled Enabled,draft_version DraftVersion,draft_validated_version DraftValidatedVersion,published_revision PublishedRevision,draft_definition_canonical Definition,created_at CreatedAt,updated_at UpdatedAt", new { tenant, name, description, definition, hash = WorkflowCanonicalizer.Hash(definition), by }, cancellationToken: ct)); return r is null ? new(OrchestratorWriteStatus.Duplicate) : new(OrchestratorWriteStatus.Success, r.ToModel()); }
    public async Task<OrchestratorWriteResult> UpdateAsync(string tenant, Guid id, long v, string name, string description, string definition, CancellationToken ct) { await using var c = await dataSource.OpenConnectionAsync(ct); var r = await c.QuerySingleOrDefaultAsync<Row>(new CommandDefinition("UPDATE orchestrator SET name=@name,description=@description,draft_definition=@definition::jsonb,draft_definition_canonical=convert_to(@definition,'UTF8'),draft_definition_sha256=@hash,draft_version=draft_version+1,draft_validated_version=NULL,updated_at=now() WHERE tenant_id=@tenant AND id=@id AND draft_version=@v RETURNING id Id,name Name,description Description,enabled Enabled,draft_version DraftVersion,draft_validated_version DraftValidatedVersion,published_revision PublishedRevision,draft_definition_canonical Definition,created_at CreatedAt,updated_at UpdatedAt", new { tenant, id, v, name, description, definition, hash = WorkflowCanonicalizer.Hash(definition) }, cancellationToken: ct)); if (r is not null) return new(OrchestratorWriteStatus.Success, r.ToModel()); var current = await c.ExecuteScalarAsync<long?>(new CommandDefinition("SELECT draft_version FROM orchestrator WHERE tenant_id=@tenant AND id=@id", new { tenant, id }, cancellationToken: ct)); return current is long version ? new(OrchestratorWriteStatus.VersionConflict, CurrentDraftVersion: version) : new(OrchestratorWriteStatus.NotFound); }
    public async Task<IReadOnlyList<string>> ValidateReferencesAsync(string tenant, string definition, CancellationToken ct) { await using var c = await dataSource.OpenConnectionAsync(ct); return await ValidateReferences(c, null, tenant, definition, false, ct); }
    public async Task<bool> MarkValidatedAsync(string tenant, Guid id, long v, string def, CancellationToken ct) { await using var c = await dataSource.OpenConnectionAsync(ct); return await c.ExecuteAsync(new CommandDefinition("UPDATE orchestrator SET draft_definition=@def::jsonb,draft_definition_canonical=convert_to(@def,'UTF8'),draft_definition_sha256=@hash,draft_validated_version=@v WHERE tenant_id=@tenant AND id=@id AND draft_version=@v", new { tenant, id, v, def, hash = WorkflowCanonicalizer.Hash(def) }, cancellationToken: ct)) == 1; }
    public async Task<OrchestratorWriteResult> PublishAsync(string tenant, Guid id, long v, string def, string by, CancellationToken ct) => await WriteRevision(tenant, id, v, def, by, null, ct);
    public async Task<IReadOnlyList<OrchestratorRevisionInfo>> RevisionsAsync(string tenant, Guid id, CancellationToken ct) { await using var c = await dataSource.OpenConnectionAsync(ct); return (await c.QueryAsync<OrchestratorRevisionInfo>(new CommandDefinition("SELECT r.revision Revision,r.status Status,r.definition_sha256 DefinitionSha256,r.created_by CreatedBy,r.created_at CreatedAt FROM orchestrator_revision r JOIN orchestrator o ON o.id=r.orchestrator_id WHERE o.tenant_id=@tenant AND o.id=@id ORDER BY r.revision DESC", new { tenant, id }, cancellationToken: ct))).AsList(); }
    public async Task<string?> RevisionAsync(string tenant, Guid id, int revision, CancellationToken ct) { await using var c = await dataSource.OpenConnectionAsync(ct); var r = await c.ExecuteScalarAsync<byte[]?>(new CommandDefinition("SELECT r.canonical_definition FROM orchestrator_revision r JOIN orchestrator o ON o.id=r.orchestrator_id WHERE o.tenant_id=@tenant AND o.id=@id AND r.revision=@revision", new { tenant, id, revision }, cancellationToken: ct)); return r is null ? null : Encoding.UTF8.GetString(r); }
    public async Task<OrchestratorWriteResult> RestoreAsync(string tenant, Guid id, int revision, string def, string by, CancellationToken ct) => await WriteRevision(tenant, id, null, def, by, revision, ct);
    public async Task<bool> SetEnabledAsync(string tenant, Guid id, bool enabled, CancellationToken ct) { await using var c = await dataSource.OpenConnectionAsync(ct); return await c.ExecuteAsync(new CommandDefinition("UPDATE orchestrator SET enabled=@enabled,updated_at=now() WHERE tenant_id=@tenant AND id=@id", new { tenant, id, enabled }, cancellationToken: ct)) == 1; }
    private async Task<OrchestratorWriteResult> WriteRevision(string tenant, Guid id, long? expected, string def, string by, int? restoring, CancellationToken ct)
    {
        var refs = Refs(def); if (refs is null) return new(OrchestratorWriteStatus.VersionConflict); await using var c = await dataSource.OpenConnectionAsync(ct); await using var tx = await c.BeginTransactionAsync(ct); var s = await c.QuerySingleOrDefaultAsync<State>(new CommandDefinition("SELECT draft_version Version,draft_validated_version Validated,published_revision Published,draft_definition_canonical Definition FROM orchestrator WHERE tenant_id=@tenant AND id=@id FOR UPDATE", new { tenant, id }, tx, cancellationToken: ct)); if (s is null) return new(OrchestratorWriteStatus.NotFound); if (expected is long e && (s.Version != e || s.Validated != e || Encoding.UTF8.GetString(s.Definition) != def)) return new(OrchestratorWriteStatus.VersionConflict); if (restoring is int old && !await c.ExecuteScalarAsync<bool>(new CommandDefinition("SELECT EXISTS(SELECT 1 FROM orchestrator_revision WHERE orchestrator_id=@id AND revision=@old)", new { id, old }, tx, cancellationToken: ct))) return new(OrchestratorWriteStatus.NotFound);
        if ((await ValidateReferences(c, tx, tenant, def, true, ct)).Count > 0) return new(OrchestratorWriteStatus.VersionConflict);
        // Pin only same-tenant enabled published revisions; locks prevent a disable/publish race.
        var workflow = await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("SELECT w.id FROM workflow w JOIN workflow_revision r ON r.workflow_id=w.id AND r.revision=@rev WHERE w.id=@wid AND w.tenant_id=@tenant AND w.enabled AND w.published_revision IS NOT NULL FOR SHARE OF w,r", new { wid = refs.Value.WorkflowId, rev = refs.Value.WorkflowRevision, tenant }, tx, cancellationToken: ct));
        var verifier = await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("SELECT a.id FROM agent a JOIN agent_revision r ON r.agent_id=a.id AND r.revision=@rev WHERE a.id=@aid AND a.tenant_id=@tenant AND a.enabled AND a.published_revision IS NOT NULL AND r.status='published' FOR SHARE OF a,r", new { aid = refs.Value.VerifierId, rev = refs.Value.VerifierRevision, tenant }, tx, cancellationToken: ct)); if (workflow is null || verifier is null) return new(OrchestratorWriteStatus.VersionConflict);
        var next = (s.Published ?? 0) + 1; var hash = WorkflowCanonicalizer.Hash(def); await c.ExecuteAsync(new CommandDefinition("UPDATE orchestrator_revision SET status='superseded' WHERE orchestrator_id=@id AND status='published'; INSERT INTO orchestrator_revision(orchestrator_id,revision,status,definition,canonical_definition,definition_sha256,workflow_id,workflow_revision,verifier_agent_id,verifier_agent_revision,created_by) VALUES(@id,@next,'published',@def::jsonb,convert_to(@def,'UTF8'),@hash,@wid,@wrev,@aid,@arev,@by); UPDATE orchestrator SET published_revision=@next,draft_validated_version=NULL,updated_at=now() WHERE id=@id", new { id, next, def, hash, wid = refs.Value.WorkflowId, wrev = refs.Value.WorkflowRevision, aid = refs.Value.VerifierId, arev = refs.Value.VerifierRevision, by }, tx, cancellationToken: ct)); await tx.CommitAsync(ct); return new(OrchestratorWriteStatus.Success, await GetAsync(tenant, id, ct), next);
    }
    private static (Guid WorkflowId, int WorkflowRevision, Guid VerifierId, int VerifierRevision)? Refs(string def) { try { using var d = JsonDocument.Parse(def); var r = d.RootElement; var w = r.GetProperty("workflow"); var a = r.GetProperty("verifier"); return (Guid.Parse(w.GetProperty("id").GetString()!), w.GetProperty("revision").GetInt32(), Guid.Parse(a.GetProperty("agentId").GetString()!), a.GetProperty("revision").GetInt32()); } catch (Exception e) when (e is JsonException or KeyNotFoundException or FormatException or InvalidOperationException) { return null; } }
    private static async Task<IReadOnlyList<string>> ValidateReferences(NpgsqlConnection c, NpgsqlTransaction? tx, string tenant, string def, bool locks, CancellationToken ct)
    {
        var errors = new List<string>(); using var graph = JsonDocument.Parse(def); var workflow = graph.RootElement.GetProperty("workflow"); var wid = Guid.Parse(workflow.GetProperty("id").GetString()!); var wrev = workflow.GetProperty("revision").GetInt32();
        var lockSql = locks ? " FOR SHARE OF w,r" : "";
        var workflowRow = await c.QuerySingleOrDefaultAsync<IntegrityRow>(new CommandDefinition("SELECT r.definition_canonical Bytes,r.definition_sha256 Sha,w.kind Kind FROM workflow w JOIN workflow_revision r ON r.workflow_id=w.id AND r.revision=@wrev WHERE w.id=@wid AND w.tenant_id=@tenant AND w.enabled AND w.published_revision=@wrev AND w.kind='orchestrator'" + lockSql, new { wid, wrev, tenant }, tx, cancellationToken: ct));
        if (workflowRow is null) errors.Add("workflow must pin active same-tenant published orchestrator kind"); else if (workflowRow.Bytes is null || !SkillHash.MatchesSha256(workflowRow.Bytes, workflowRow.Sha)) errors.Add("workflow revision canonical integrity check failed");
        foreach (var reference in OrchestratorCanonicalizer.AgentRefs(def))
        {
            var row = await c.QuerySingleOrDefaultAsync<IntegrityRow>(new CommandDefinition("SELECT r.canonical_definition Bytes,r.definition_sha256 Sha,'' Kind,r.runtime_workflow_id RuntimeWorkflowId,r.runtime_workflow_revision RuntimeWorkflowRevision FROM agent a JOIN agent_revision r ON r.agent_id=a.id AND r.revision=@revision WHERE a.id=@id AND a.tenant_id=@tenant AND a.enabled AND a.published_revision=@revision AND r.status='published'" + (locks ? " FOR SHARE OF a,r" : ""), new { id = reference.AgentId, revision = reference.Revision, tenant }, tx, cancellationToken: ct));
            if (row is null) { errors.Add($"agent {reference.AgentId:D} must pin active same-tenant published revision"); continue; }
            if (row.Bytes is null || !SkillHash.MatchesSha256(row.Bytes, row.Sha)) { errors.Add($"agent {reference.AgentId:D} canonical integrity check failed"); continue; }
            try { var canonical = Encoding.UTF8.GetString(row.Bytes); errors.AddRange(OrchestratorReferencePolicy.ValidateAgentDefinition(canonical, reference)); errors.AddRange(OrchestratorReferencePolicy.ValidateRuntimeWorkflowProjection(canonical, row.RuntimeWorkflowId, row.RuntimeWorkflowRevision)); } catch (Exception) { errors.Add($"agent {reference.AgentId:D} canonical definition is corrupt"); }
            if (reference.Verifier) errors.AddRange(await ValidateVerifierWorkflow(c, tx, tenant, row, locks, ct));
        }
        return errors;
    }
    private static async Task<IReadOnlyList<string>> ValidateVerifierWorkflow(NpgsqlConnection c, NpgsqlTransaction? tx, string tenant, IntegrityRow agent, bool locks, CancellationToken ct)
    {
        if (agent.RuntimeWorkflowId is not Guid workflowId || agent.RuntimeWorkflowRevision is not int revision) return ["verifier Agent revision must pin a verifier agent-runtime Workflow revision"];
        var row = await c.QuerySingleOrDefaultAsync<IntegrityRow>(new CommandDefinition("SELECT r.definition_canonical Bytes,r.definition_sha256 Sha,w.kind Kind,r.compiler_contract_version CompilerContractVersion FROM workflow w JOIN workflow_revision r ON r.workflow_id=w.id AND r.revision=@revision WHERE w.id=@workflowId AND w.tenant_id IN (@tenant,@systemTenant) AND w.enabled AND w.kind='agent-runtime'" + (locks ? " FOR SHARE OF w,r" : ""), new { workflowId, revision, tenant, systemTenant = Backend.Api.Agents.AgentDefaults.SystemTenant }, tx, cancellationToken: ct));
        if (row is null) return ["verifier Agent revision must pin a visible agent-runtime Workflow revision"];
        if (row.Bytes is null || !SkillHash.MatchesSha256(row.Bytes, row.Sha)) return ["verifier Agent runtime Workflow canonical integrity check failed"];
        return OrchestratorReferencePolicy.ValidateVerifierWorkflowDefinition(Encoding.UTF8.GetString(row.Bytes), row.CompilerContractVersion);
    }
    private sealed record Row(Guid Id, string Name, string Description, bool Enabled, long DraftVersion, long? DraftValidatedVersion, int? PublishedRevision, byte[] Definition, DateTime CreatedAt, DateTime UpdatedAt) { public Orchestrator ToModel() => new(Id, Name, Description, Enabled, DraftVersion, DraftValidatedVersion, PublishedRevision, Encoding.UTF8.GetString(Definition), CreatedAt, UpdatedAt); }
    private sealed record State(long Version, long? Validated, int? Published, byte[] Definition);
    private sealed class IntegrityRow
    {
        public byte[]? Bytes { get; init; }
        public string? Sha { get; init; }
        public string Kind { get; init; } = "";
        public Guid? RuntimeWorkflowId { get; init; }
        public int? RuntimeWorkflowRevision { get; init; }
        public string? CompilerContractVersion { get; init; }
    }
}
