using Backend.Api.Common;
using Backend.Api.Workflows;
using Microsoft.AspNetCore.Mvc;

namespace Backend.Api.Orchestrators;

[ApiController, Route("api/admin/orchestrators")]
public sealed class OrchestratorController(IOrchestratorRepository repo, IWorkflowCompiler compiler) : ControllerBase
{
    [HttpGet] public async Task<IActionResult> List(CancellationToken ct) { Guard(); return Ok(await repo.ListAsync(Request.RequireTenant(), ct)); }
    [HttpGet("{id:guid}")] public async Task<IActionResult> Get(Guid id, CancellationToken ct) { Guard(); return OkTag(await repo.GetAsync(Request.RequireTenant(), id, ct) ?? throw Missing(id)); }
    [HttpPost] public async Task<IActionResult> Create(OrchestratorUpsert x, CancellationToken ct) { Guard(); var e = Errors(x); if (e.Count > 0) throw Bad(e); var r = await repo.CreateAsync(Request.RequireTenant(), Need(x.Name, "name"), x.Description ?? "", OrchestratorCanonicalizer.Canonicalize(x.Definition), Request.UserIdOrEmpty(), ct); if (r.Status == OrchestratorWriteStatus.Duplicate) throw new ApiException(409, "Orchestrator name already exists"); return Created($"/api/admin/orchestrators/{r.Orchestrator!.Id}", Tag(r.Orchestrator)); }
    [HttpPut("{id:guid}/draft")] public async Task<IActionResult> Update(Guid id, OrchestratorUpsert x, CancellationToken ct) { Guard(); var e = Errors(x); if (e.Count > 0) throw Bad(e); var r = await repo.UpdateAsync(Request.RequireTenant(), id, Version(), Need(x.Name, "name"), x.Description ?? "", OrchestratorCanonicalizer.Canonicalize(x.Definition), ct); return r.Status switch { OrchestratorWriteStatus.NotFound => throw Missing(id), OrchestratorWriteStatus.VersionConflict => throw Stale(), _ => OkTag(r.Orchestrator!) }; }
    [HttpPost("{id:guid}/validate")] public async Task<IActionResult> Validate(Guid id, CancellationToken ct) { Guard(); var t = Request.RequireTenant(); var v = Version(); var o = await repo.GetAsync(t, id, ct) ?? throw Missing(id); if (o.DraftVersion != v) throw Stale(); var e = await ValidateAll(t, o.Definition, ct); if (e.Count == 0 && !await repo.MarkValidatedAsync(t, id, v, o.Definition, ct)) throw Stale(); Response.SetVersionETag(v); return Ok(new { valid = e.Count == 0, errors = e }); }
    [HttpPost("{id:guid}/publish")] public async Task<IActionResult> Publish(Guid id, OrchestratorPublishRequest x, CancellationToken ct) { Guard(); var t = Request.RequireTenant(); var v = Version(); if (x.ExpectedDraftVersion != v) throw new ApiException(400, "If-Match and expected_draft_version must match"); var o = await repo.GetAsync(t, id, ct) ?? throw Missing(id); if (o.DraftValidatedVersion != v) throw Stale(); var e = await ValidateAll(t, o.Definition, ct); if (e.Count > 0) throw Bad(e); var r = await repo.PublishAsync(t, id, v, o.Definition, Request.UserIdOrEmpty(), ct); if (r.Status == OrchestratorWriteStatus.VersionConflict) throw Stale(); return OkTag(r.Orchestrator!); }
    [HttpGet("{id:guid}/revisions")] public async Task<IActionResult> Revisions(Guid id, CancellationToken ct) { Guard(); return Ok(await repo.RevisionsAsync(Request.RequireTenant(), id, ct)); }
    [HttpPost("{id:guid}/revisions/{revision:int}/restore")] public async Task<IActionResult> Restore(Guid id, int revision, CancellationToken ct) { Guard(); var t = Request.RequireTenant(); var d = await repo.RevisionAsync(t, id, revision, ct) ?? throw Missing(id); var e = await ValidateAll(t, d, ct); if (e.Count > 0) throw Bad(e); var r = await repo.RestoreAsync(t, id, revision, d, Request.UserIdOrEmpty(), ct); return OkTag(r.Orchestrator!); }
    [HttpDelete("{id:guid}")] public async Task<IActionResult> Disable(Guid id, CancellationToken ct) { Guard(); if (!await repo.SetEnabledAsync(Request.RequireTenant(), id, false, ct)) throw Missing(id); return NoContent(); }
    [HttpPost("{id:guid}/enable")] public async Task<IActionResult> Enable(Guid id, CancellationToken ct) { Guard(); var t = Request.RequireTenant(); if (!await repo.SetEnabledAsync(t, id, true, ct)) throw Missing(id); return OkTag((await repo.GetAsync(t, id, ct))!); }
    private async Task<List<string>> ValidateAll(string tenant, string definition, CancellationToken ct) { var shape = OrchestratorCanonicalizer.Validate(definition); var errors = shape.Concat(await repo.ValidateReferencesAsync(tenant, definition, ct)).ToList(); if (shape.Count == 0) errors.AddRange(OrchestratorCanonicalizer.ValidateContextTools(definition, await compiler.ToolsAsync(tenant, ct))); return errors.Distinct().ToList(); }
    private void Guard() => Request.RequireCapability("workflow.manage");
    private long Version() => Request.RequireIfMatchVersion();
    private IActionResult OkTag(Orchestrator x) => Ok(Tag(x));
    private object Tag(Orchestrator x) { Response.SetVersionETag(x.DraftVersion); return OrchestratorResponse.From(x); }
    private static List<string> Errors(OrchestratorUpsert x) => OrchestratorCanonicalizer.Validate(OrchestratorCanonicalizer.Canonicalize(x.Definition)).ToList(); private static string Need(string? v, string f) => !string.IsNullOrWhiteSpace(v) ? v.Trim() : throw new ApiException(400, $"{f} is required"); private static ApiException Missing(Guid id) => ApiErrors.NotFound(" Orchestrator", id); private static ApiException Stale() => new(409, "Orchestrator draft has changed or was not validated"); private static ApiException Bad(IEnumerable<string> e) => new ApiException(422, "Orchestrator validation failed") { FieldErrors = e.ToDictionary(x => x, x => x) };
}
