import { expect, test } from '@playwright/test'
import { evidenceUsers, signIn } from './helpers/auth'
import { concatFramedContent, readBrowserStream } from './helpers/streaming'

interface StreamCase {
  name: string
  path: string
  streamKind: 'chat' | 'agui'
  controlledContent: string[]
  method: string
  body: string
  useBrowserSession: boolean
}

function streamCases(): StreamCase[] {
  const rawCases = process.env.EVIDENCE_STREAM_CASES_JSON
  if (rawCases) {
    const parsed = JSON.parse(rawCases) as StreamCase[]
    if (!Array.isArray(parsed) || parsed.length === 0) {
      throw new Error('EVIDENCE_STREAM_CASES_JSON must contain at least one stream case')
    }
    return parsed
  }

  const streamPath = process.env.EVIDENCE_STREAM_PATH
  const streamBody = process.env.EVIDENCE_STREAM_BODY_JSON
  if (!streamPath || streamBody === undefined) return []
  return [{
    name: 'legacy stream case',
    path: streamPath,
    streamKind: 'chat',
    controlledContent: ['evidence', 'model', 'reply'],
    method: process.env.EVIDENCE_STREAM_METHOD ?? 'POST',
    body: streamBody,
    useBrowserSession: process.env.EVIDENCE_STREAM_USE_SESSION === '1',
  }]
}

/**
 * Selects the controlled-content frames for a case and keeps both a trimmed `content` (for
 * ordering/membership checks, where a token's own incidental whitespace never matters) and the
 * raw, un-stripped `data:`-suffix text (for the byte-level framing check below, where it does).
 */
function controlledContentFrames(evidence: Awaited<ReturnType<typeof readBrowserStream>>, streamCase: StreamCase) {
  if (streamCase.streamKind === 'chat') {
    return evidence.events
      .filter((frame) => frame.event !== 'error' && frame.data.trim() !== '[DONE]')
      .filter((frame) => streamCase.controlledContent.includes(frame.data.trim()))
      .map((frame) => ({ content: frame.data.trim(), raw: frame.data, offsetMs: frame.offsetMs }))
  }

  return evidence.events.flatMap((frame) => {
    try {
      const agui = JSON.parse(frame.data) as { type?: unknown, delta?: unknown }
      if (agui.type !== 'TEXT_MESSAGE_CONTENT' || typeof agui.delta !== 'string') return []
      const content = agui.delta.trim()
      return streamCase.controlledContent.includes(content)
        ? [{ content, raw: frame.data, offsetMs: frame.offsetMs }]
        : []
    } catch {
      return []
    }
  })
}

function streamHeaders(streamBody: string): Record<string, string> {
  const raw = process.env.EVIDENCE_STREAM_HEADERS_JSON
  const defaults = {
    Accept: 'text/event-stream',
    ...(streamBody === undefined ? {} : { 'Content-Type': 'application/json' }),
  }
  if (!raw) return defaults
  const headers = JSON.parse(raw) as Record<string, string>
  if (Object.keys(headers).some((name) => /^(authorization|cookie)$/i.test(name))) {
    throw new Error('EVIDENCE_STREAM_HEADERS_JSON must not contain Authorization or Cookie')
  }
  return { ...defaults, ...headers }
}

test.describe('E-06 browser ReadableStream evidence', () => {
  test('reader receives delayed frames before completion', async ({ page }) => {
    const cases = streamCases()
    // The deterministic evidence lane supplies same-origin exact payloads. A missing case is
    // surfaced as SKIP so the outer release gate reports BLOCKED rather than fabricating timing.
    test.skip(cases.length === 0, 'EVIDENCE_STREAM_CASES_JSON is required; outer evidence gate must mark BLOCKED')

    // Sign in once, outside the loop: signIn() asserts the login page is visible before
    // submitting credentials, which only holds pre-login. A per-case signIn broke as soon as a
    // second case also needed useBrowserSession=true, because the first case's login already
    // left an authenticated session in localStorage for the rest of this page's lifetime.
    if (cases.some((streamCase) => streamCase.useBrowserSession)) await signIn(page, evidenceUsers.a)
    else await page.goto('/')

    for (const streamCase of cases) {
      const evidence = await readBrowserStream(page, {
        path: streamCase.path,
        method: streamCase.method,
        headers: streamHeaders(streamCase.body),
        body: streamCase.body,
        includeSessionBearer: streamCase.useBrowserSession,
      })
      expect(evidence.status, streamCase.name).toBe(200)
      // Transport chunks may legitimately coalesce. Count only complete protocol events whose
      // content is generated by the controlled evidence model, never error/[DONE]/lifecycle
      // frames. This makes a buffered stream red and a chunk-boundary variation harmless.
      const frames = controlledContentFrames(evidence, streamCase)
      expect(frames.length, streamCase.name).toBeGreaterThanOrEqual(3)
      expect(frames.map((frame) => frame.content), streamCase.name).toEqual(streamCase.controlledContent)
      // Byte-level framing check: root AGENTS.md requires `/api/chat/stream` to write `data:`
      // (no space) and AG-UI to write `data: ` (with space). A per-frame guess at which prefix was
      // used is unsound the moment a controlled-model token itself starts with a space (real
      // tokenizer output — infra/evidence/evidence_model.py), because `data:` + `" model"` and
      // `data: ` + `"model"` are byte-identical. So the framing to strip is declared by
      // `streamCase.streamKind` (this test's own request, not the content), and the proof is that
      // stripping it and re-joining the controlled model's own reply reproduces it verbatim — any
      // framing mismatch surfaces as extra/missing/garbled bytes here, never a guess.
      const reconstructed = concatFramedContent(
        frames.map((frame) => ({ data: frame.raw })),
        streamCase.streamKind,
      )
      expect(reconstructed, streamCase.name).toBe(streamCase.controlledContent.join(' '))
      expect(frames.at(-1)!.offsetMs, streamCase.name).toBeLessThan(evidence.completedMs)

      const firstToLastMs = frames.at(-1)!.offsetMs - frames[0].offsetMs
      expect(firstToLastMs, streamCase.name).toBeGreaterThanOrEqual(400)
    }
  })
})
